services:
  - type: web
    name: pazarlio-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://civanelismail571:Hirciv19@pazarlio2.kegaoz4.mongodb.net/ilan-db?retryWrites=true&w=majority&appName=pazarLio2
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true 